const API_VERSION_URL = "v1";

const DEPARTMENT_URL = `${API_VERSION_URL}/departments`;

const LIST_DEPARTMENT_URL = DEPARTMENT_URL;
const CREATE_DEPARTMENT_URL = DEPARTMENT_URL;
const SHOW_DEPARTMENT_URL = DEPARTMENT_URL + "/{id}";
const UPDATE_DEPARTMENT_URL = DEPARTMENT_URL + "/{id}";
const DELETE_DEPARTMENT_URL = DEPARTMENT_URL + "/{id}";
const LIST_DEPARTMENT_FILTERS_URL = DEPARTMENT_URL+'/columns-filters';


export {
  LIST_DEPARTMENT_URL,
  CREATE_DEPARTMENT_URL,
  SHOW_DEPARTMENT_URL,
  UPDATE_DEPARTMENT_URL,
  DELETE_DEPARTMENT_URL,
  LIST_DEPARTMENT_FILTERS_URL
};
