import { createAction } from "@reduxjs/toolkit";
import { departmentActionTypes as actions } from "../action-types/department";

const LIST_UPDATE_PARAMS_ACTION = createAction<any, string>(
  actions.LIST_UPDATE_PARAMS
);

//Crear DEPARTMENT
const CREATE_DEPARTMENT_REQUESTED_ACTION = createAction<any>(
  actions.CREATE_DEPARTMENT_REQUESTED
);
const CREATE_DEPARTMENT_SUCCESS_ACTION = createAction<any, string>(
  actions.CREATE_DEPARTMENT_SUCCESS
);
const CREATE_DEPARTMENT_ERROR_ACTION = createAction<any, string>(
  actions.CREATE_DEPARTMENT_ERROR
);

//Listar DEPARTMENTes
const LIST_DEPARTMENT_REQUESTED_ACTION = createAction<any | undefined>(
  actions.LIST_DEPARTMENT_REQUESTED
);
const LIST_DEPARTMENT_SUCCESS_ACTION = createAction<any, string>(
  actions.LIST_DEPARTMENT_SUCCESS
);
const LIST_DEPARTMENT_ERROR_ACTION = createAction<any, string>(
  actions.LIST_DEPARTMENT_ERROR
);

//Obtener DEPARTMENT
const GET_DEPARTMENT_REQUESTED_ACTION = createAction<any, string>(
  actions.GET_DEPARTMENT_REQUESTED
);
const GET_DEPARTMENT_SUCCESS_ACTION = createAction<any, string>(
  actions.GET_DEPARTMENT_SUCCESS
);
const GET_DEPARTMENT_ERROR_ACTION = createAction<any, string>(
  actions.GET_DEPARTMENT_ERROR
);

//Actualizar
const UPDATE_DEPARTMENT_REQUESTED_ACTION = createAction<any, string>(
  actions.UPDATE_DEPARTMENT_REQUESTED
);
const UPDATE_DEPARTMENT_SUCCESS_ACTION = createAction<any, string>(
  actions.UPDATE_DEPARTMENT_SUCCESS
);
const UPDATE_DEPARTMENT_ERROR_ACTION = createAction<any, string>(
  actions.UPDATE_DEPARTMENT_ERROR
);

//eliminar
const DELETE_DEPARTMENT_REQUESTED_ACTION = createAction<any>(
  actions.DELETE_DEPARTMENT_REQUESTED
);
const DELETE_DEPARTMENT_SUCCESS_ACTION = createAction<any, string>(
  actions.DELETE_DEPARTMENT_SUCCESS
);
const DELETE_DEPARTMENT_ERROR_ACTION = createAction<any, string>(
  actions.DELETE_DEPARTMENT_ERROR
);

//Listar DEPARTMENTes
const LIST_DEPARTMENT_FILTERS_REQUESTED_ACTION = createAction<any | undefined>(
  actions.LIST_DEPARTMENT_FILTERS_REQUESTED
);
const LIST_DEPARTMENT_FILTERS_SUCCESS_ACTION = createAction<any, string>(
  actions.LIST_DEPARTMENT_FILTERS_SUCCESS
);
const LIST_DEPARTMENT_FILTERS_ERROR_ACTION = createAction<any, string>(
  actions.LIST_DEPARTMENT_FILTERS_ERROR
);

export {
  LIST_UPDATE_PARAMS_ACTION,

  CREATE_DEPARTMENT_REQUESTED_ACTION,
  CREATE_DEPARTMENT_SUCCESS_ACTION,
  CREATE_DEPARTMENT_ERROR_ACTION,

  LIST_DEPARTMENT_REQUESTED_ACTION,
  LIST_DEPARTMENT_SUCCESS_ACTION,
  LIST_DEPARTMENT_ERROR_ACTION,

  GET_DEPARTMENT_REQUESTED_ACTION,
  GET_DEPARTMENT_SUCCESS_ACTION,
  GET_DEPARTMENT_ERROR_ACTION,

  UPDATE_DEPARTMENT_REQUESTED_ACTION,
  UPDATE_DEPARTMENT_SUCCESS_ACTION,
  UPDATE_DEPARTMENT_ERROR_ACTION,
  
  DELETE_DEPARTMENT_REQUESTED_ACTION,
  DELETE_DEPARTMENT_SUCCESS_ACTION,
  DELETE_DEPARTMENT_ERROR_ACTION,

  LIST_DEPARTMENT_FILTERS_REQUESTED_ACTION,
  LIST_DEPARTMENT_FILTERS_SUCCESS_ACTION,
  LIST_DEPARTMENT_FILTERS_ERROR_ACTION,
};
