export const departmentActionTypes = {
  CREATE_DEPARTMENT_REQUESTED: "[DEPARTMENT] Create DEPARTMENT requested",
  CREATE_DEPARTMENT_SUCCESS: "[DEPARTMENT] Create DEPARTMENT success",
  CREATE_DEPARTMENT_ERROR: "[DEPARTMENT] Create DEPARTMENT failed",

  LIST_DEPARTMENT_REQUESTED: "[DEPARTMENT] List DEPARTMENTs requested",
  LIST_DEPARTMENT_SUCCESS: "[DEPARTMENT] List DEPARTMENTs success",
  LIST_DEPARTMENT_ERROR: "[DEPARTMENT] List DEPARTMENTs failed",

  LIST_UPDATE_PARAMS: "[DEPARTMENT] List DEPARTMENTs update params",

  GET_DEPARTMENT_REQUESTED: "[DEPARTMENT] Get DEPARTMENT requested",
  GET_DEPARTMENT_SUCCESS: "[DEPARTMENT] Get DEPARTMENT success",
  GET_DEPARTMENT_ERROR: "[DEPARTMENT] Get DEPARTMENT failed",

  UPDATE_DEPARTMENT_REQUESTED: "[DEPARTMENT] Update DEPARTMENT requested",
  UPDATE_DEPARTMENT_SUCCESS: "[DEPARTMENT] Update DEPARTMENT success",
  UPDATE_DEPARTMENT_ERROR: "[DEPARTMENT] Update DEPARTMENT failed",

  DELETE_DEPARTMENT_REQUESTED: "[DEPARTMENT] Delete DEPARTMENT requested",
  DELETE_DEPARTMENT_SUCCESS: "[DEPARTMENT] Delete DEPARTMENT success",
  DELETE_DEPARTMENT_ERROR: "[DEPARTMENT] Delete DEPARTMENT failed",

  LIST_DEPARTMENT_FILTERS_REQUESTED: "[DEPARTMENT] List DEPARTMENTs filters requested",
  LIST_DEPARTMENT_FILTERS_SUCCESS: "[DEPARTMENT] List DEPARTMENTs filters success",
  LIST_DEPARTMENT_FILTERS_ERROR: "[DEPARTMENT] List DEPARTMENTs filters failed",
};
